### ISSUE TITLE
🇬🇧 l10n

### ISSUE THREAD

**Issue by mro** [mro/ShaarliGo#20]
currently it's a germenglish mess.

**Comment by frenchvandal** [comment]
I have yet to install the new ShaarliGo update on my webserver to do a proper double check.

Here are a few things from what I see in the demo, I would suggest the following modifications in the EN translation:
- Days -> Daily
- Search word or #tag… -> Search text or #tag… 
- Logon -> Login (logon is actually correct too but login is more commonly used imho)

And a little aesthetics enhancement: maybe remove automatically the comma `,` after the last tag of the list?

![image](https://user-images.githubusercontent.com/42499534/80353125-2f0aa780-8875-11ea-9ac2-7ae4d20ddb73.png)

**Comment by mro** [comment]
removing the comma adds too much complexity I think. Currently it's trivial https://github.com/mro/ShaarliGo/blob/997e36f0f0ae2b51c9388f3dae6bf0fc37662c99/static/themes/current/posts.xslt#L366 – I don't know how to do otherwise (preferably in a simple manner).

**Comment by frenchvandal** [comment]
Maybe something like [that](https://stackoverflow.com/questions/17094826/remove-last-comma-in-xslt) but it is not that important to have a comma at the end of the tag list 😉 

Better keep the code simple!

**Comment by mro** [comment]
That's simple! cgis updated.

**Comment by mro** [comment]
good for now, in case reopen.
