### ISSUE TITLE
research: storage in existing, single, uncompressed posts (index.xml)

### ISSUE THREAD

**Issue by mro** [mro/ShaarliGo#22]
rather than in one central file.

**Comment by mro** [comment]
compressing the myriad of files may not be worth while. Sample from l.mro.name, ncdu numbers:

```
Filesystem (ext4)

o/ gzip compressed:
Total disk usage: 126.8MiB  Apparent size:  85.2MiB  Items: 31028

o/ uncompressed:
Total disk usage: 171.1MiB  Apparent size: 141.3MiB  Items: 31028
```

**Comment by mro** [comment]
I favor of less complexity I shall drop (storage) compression.

**Comment by mro** [comment]
see 767f087287

**Comment by mro** [comment]
see 767f087, requires a document migration:

    $ find o -name index.xml.gz -exec gunzip {} \;

and asset refresh (`.htaccess`).

**Comment by mro** [comment]
@frenchvandal do you think we could do this transition now before you actually start using it?

**Comment by frenchvandal** [comment]
> @frenchvandal do you think we could do this transition now before you actually start using it?

You mean the French translation, or checking the English one?
I have yet to install the new shaarligo.cgi file.
Also I am running some tests to serve the app with lighttpd instead of Apache, it seems a better solution. Just a little more work because Apache has an official Docker image, and I have to create my own image for lighttpd. I have been on it since his morning. Normally it should not be too complicated 😉

**Comment by mro** [comment]
@frenchvandal no, I don't mean translation, I meant transition – from having gzip compressed xml files for publication (was so in the past) to "natural", uncompressed `index.xml` files with single posts and feeds.

So I understand you, that it's ok to start fresh.

I'll update the download cgi binaries.

**Comment by frenchvandal** [comment]
Sorry I woke up early this morning and was still a bit sleepy! I read too fast 😆 

No worries, I am still in a testing phase and I will migrate to a new smaller VPS by the end of week. So not yet using ShaarliGo in production!

**Comment by mro** [comment]
🎉
