### ISSUE TITLE
ShaarliGo with Nginx

### ISSUE THREAD

**Issue by frenchvandal** [mro/ShaarliGo#24]
@mro Can you assign me this issue?

I will try to serve ShaarliGo with Nginx. If all goes well, I will post an example config in the comments.

Nginx does not support CGI but theoretically this should work with a third party interpreter like fcgiwrap or uWSCI.

As a starting point, some random resources to execute an old school CGI script with Nginx:

https://www.nginx.com/resources/wiki/start/topics/examples/fcgiwrap/
https://blog.sleeplessbeastie.eu/2017/09/18/how-to-execute-cgi-scripts-using-fcgiwrap/
https://static.cinay.xyz/2019/09/Nginx-scripts-CGI-fcgiwrap.html#utiliser-un-seul-script-cgi
https://stackoverflow.com/questions/11667489/how-to-run-cgi-scripts-on-nginx
https://uwsgi-docs.readthedocs.io/en/latest/CGI.html

**Comment by mro** [comment]
be aware that cgi != fcgi

**Comment by frenchvandal** [comment]
Yes I guessed so. As far as I understood, Nginx can handle fcgi natively but not cgi. You need an interpreter for that, but you can use the same directives as fcgi in conf.

Fow now it is starting good!

With fcgiwrap installed, I managed to have shaarligo.cgi executed by nginx and all the files are decompressed:

![image](https://user-images.githubusercontent.com/42499534/80918882-6e4e6200-8d67-11ea-8dce-0e406b218264.png)

Nginx is caught in an infinite loop:
```
nginx    | 172.19.0.2 - - [03/May/2020:15:45:12 +0000] "GET /shaarligo.cgi/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/config/ HTTP/1.1" 303 327 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36" "172.19.0.1:56216"
```
I think now I have to rewrite all the Apache directives into Nginx format.

**Comment by mro** [comment]
are you making progress?

**Comment by frenchvandal** [comment]
No, I am very sorry, no luck. I tried but I was stuck with nginx. The docs I found were optimized for FastCGI. Not all modern web servers seem to be working easily with old school CGI.

**Comment by mro** [comment]
hm, sad, so lighttpd may be the lightest to get. I am suprised nginx won't do cgi.

**Comment by mro** [comment]
maybe thttpd could come to a rescue: https://searx.info/?q=nginx%20cgi%20thttpd
