### ISSUE TITLE
🇫🇷 i18n

### ISSUE THREAD

**Issue by frenchvandal** [mro/ShaarliGo#25]
Translating the ShaarliGo theme into French.

@mro can you assign me this one? I will do a pull request when I am done, or send you the new assets in a zip file.

**Comment by mro** [comment]
great, either way is fine, zipped assets, fork+pull request or even a running demo where I can just HTTP GET the assets (curl/wget).

**Comment by mro** [comment]
Hi, @frenchvandal how's it going?

**Comment by mro** [comment]
@frenchvandal ready?

**Comment by mro** [comment]
Hi @frenchvandal, how's it going?

**Comment by frenchvandal** [comment]
Hi @mro I am very sorry man for my silence. I have been on sick leave for almost 3 months after a burnout at my job. Now I am back on track, for the best.

I will resume the translation, not complicated, just a matter of focusing on the task for 1 hour or so.

**Comment by mro** [comment]
no hurries, get well, enjoy an a bit strange summer and post the translated shaarligo here once you're comfortable with it. I'll grab the resources then.

**Comment by mro** [comment]
relax and reopen once ready.
