### ISSUE TITLE
Remove lighthttpd dependency

### ISSUE THREAD

**Issue by etopeter** [mro/ShaarliGo#6]
This is feature request:
It would be great to have sharligo as a single binary without having to install and configure lighthttpd or other webservers.

**Comment by mro** [comment]
I consider it a feature to not serve HTTP request wo strangers. Maybe the search will be restricted to logged-in users (= the owner).

So it's a design decision to not mimic a webserver.

**Comment by mro** [comment]
@etopeter what is your usecase in which you cannot afford a webserver?

**Comment by etopeter** [comment]
I see it as a opinionated dependency. It would be much better let user decide what to put in front of application server. Popular choices are apache and nginx which are industry standard. Why not making it listen on some port like tomcat or unicorn does and let the proxy of your choice forward traffic?

**Comment by mro** [comment]
there seems to be a misunderstanding.

Which dependency to which webserver do you see?

There are 2 webserver configurations coming out of the box (apache and lighttpd). Any opinionated other webserver choice should be fairly easy to configure, starting with the two quite different examples.

**Comment by mro** [comment]
@etopeter does https://github.com/mro/ShaarliGo#dependencies clarify things?
